services:
  back-end:
    build: ./back-end
    ports:
      - "8000:8000"
    env_file:
      - ./back-end/.env
    networks:
      - app_network

  front-end:
    build: ./front-end
    ports:
      - "8080:80"
    depends_on:
      - back-end
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
